services:
  - type: worker
    name: groq-langchain-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GROQ_API_KEY
        sync: false  # You'll add the value manually in the dashboard
